name: Svelte Cat Generator CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-format-test:
    runs-on: ubuntu-latest
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: './svelte-cat-generator/package-lock.json'
          
      - name: Install Svelte dependencies
        run: |
          cd ./svelte-cat-generator
          npm i
        
      - name: Check linting
        run: |
          cd ./svelte-cat-generator
          npm run lint
        
      - name: Check formatting
        run: |
          cd ./svelte-cat-generator
          npm run format:check
        
      - name: Run tests
        run: |
          cd ./svelte-cat-generator
          npm run test:unit

      - name: Install Root dependencies
        run: |
          npm i
          npx playwright install --with-deps

      - name: Build
        run: |
          cd ./svelte-cat-generator
          npm run build

      - name: Run E2E tests
        run: npm run test:e2e


  deploy:
    name: Deploy to Netlify
    needs: [lint-format-test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Build Svelte App
        run: |
          cd svelte-cat-generator
          npm install
          npm run build

      - name: Deploy Svelte to Netlify
        run: |
          npx netlify deploy --prod --dir=svelte-cat-generator/dist --site=${{ secrets.NETLIFY_SITE_ID_SVELTE }} --auth=${{ secrets.NETLIFY_TOKEN }}